dist: xenial
sudo: required
language: python
cache:
  pip: true

services:
  - postgresql
  - rabbitmq
  - redis

python:
  - 3.6
  - 3.7

before_script:
  - mv django_ml_spam_filter/config.travis.py django_ml_spam_filter/config.py
  - psql -c 'CREATE ROLE test;' -U postgres
  - psql -c 'ALTER ROLE test WITH SUPERUSER;' -U postgres
  - psql -c 'ALTER ROLE test WITH LOGIN;' -U postgres
  - psql -c "ALTER ROLE test PASSWORD 'test';" -U postgres
  - psql -c 'CREATE DATABASE testdb OWNER test;' -U postgres

script:
  python runtests.py